import { Hono } from 'hono'
import { serveStatic } from 'hono/cloudflare-pages'

const app = new Hono()
app.use('/static/*', serveStatic())

const themes = [
  { id: 'genre', number: '01', title: 'Genre & réduction des inégalités', short: 'Faire reculer les inégalités par des stratégies ancrées dans les réalités locales.', icon: 'fa-venus-mars', color: 'green' },
  { id: 'gouvernance', number: '02', title: 'Politiques publiques & gouvernance', short: 'Renforcer la redevabilité, les droits et la décision publique.', icon: 'fa-landmark', color: 'blue' },
  { id: 'communication', number: '03', title: 'Communication & marketing social', short: 'Transformer les messages en mobilisation et en changements observables.', icon: 'fa-bullhorn', color: 'orange' },
  { id: 'management', number: '04', title: 'Management des projets', short: 'Passer de l’intention à l’impact avec méthode et pilotage.', icon: 'fa-diagram-project', color: 'purple' },
  { id: 'decentralisation', number: '05', title: 'Décentralisation & gouvernance locale', short: 'Outiller les territoires pour décider, agir et rendre compte.', icon: 'fa-city', color: 'teal' },
  { id: 'intermediation', number: '06', title: 'Intermédiation commerciale & financière', short: 'Créer des passerelles entre acteurs, marchés et ressources.', icon: 'fa-arrows-to-circle', color: 'gold' },
  { id: 'terrain', number: '07', title: 'De la théorie à la pratique', short: 'Mettre les compétences en mouvement sur le terrain.', icon: 'fa-route', color: 'red' },
]

const formations = [
  ['01','genre','Mobilisation communautaire contre les VBG et mécanismes de prévention et de prise en charge des survivant(e)s victimes de VBG','3','75 000 FCFA'],
  ['02','genre','Plaidoyer et mobilisation communautaire en faveur du renforcement de la cohésion sociale et de la résilience des populations vulnérables dans un contexte de déficit sécuritaire','3','75 000 FCFA'],
  ['03','genre','Stratégie de plaidoyer pour la promotion et la vulgarisation des textes et des instruments nationaux et internationaux favorables aux droits et à l’épanouissement des femmes','3','75 000 FCFA'],
  ['04','genre','Stratégie de plaidoyer pour accélérer l’égalité de genre dans les communautés religieuses, traditionnelles et dans les collectivités décentralisées','3','75 000 FCFA'],
  ['05','genre','Stratégie intégrée de Plaidoyer et de CCC pour la promotion de la Gestion Hygiénique des Matières (GHM)','3','75 000 FCFA'],
  ['06','genre','Planification et budgétisation de projet de développement genre sensible','2','75 000 FCFA'],
  ['07','genre','Audits / Évaluations d’impacts genre sensible des projets de développement','2','75 000 FCFA'],
  ['08','genre','Formation sur le leadership genre et la prise de parole en public','2','75 000 FCFA'],
  ['01','gouvernance','Renforcement des capacités des parlementaires sur le droit à l’Alimentation, la Redevabilité et l’Approche Basée sur les Droits Humains (ABDH)','3','75 000 FCFA'],
  ['02','gouvernance','Renforcement de la gouvernance locale et rurale en faveur de l’autosuffisance alimentaire et de l’atteinte du droit à une alimentation adéquate','3','75 000 FCFA'],
  ['03','gouvernance','Formation et renforcement des capacités des formateurs endogènes sur la redevabilité, la mise en place de mécanismes de redevabilité et de gestion des plaintes formulées par les bénéficiaires et les usagers','3','75 000 FCFA'],
  ['04','gouvernance','Accompagnement et renforcement des capacités de Plaidoyer des coopératives et des organisations de production, de transformation et de commercialisation pour leur appropriation de la gouvernance des collectivités et la consolidation des pôles de croissance économique','3','75 000 FCFA'],
  ['05','gouvernance','Conduite d’une stratégie de Plaidoyer pour l’adoption et l’effectivité d’une Approche différenciée de prestations à l’endroit des adolescents et jeunes adultes nés/vivant avec le VIH pour l’élimination de la stigmatisation et de la discrimination liée au statut sérologique','2','75 000 FCFA'],
  ['06','gouvernance','Formation et Renforcement des Capacités des leaders des associations et des OSC en technique de recherche des financements et en Mobilisation endogène des Ressources','2','50 000 FCFA'],
  ['07','gouvernance','Organisation d’ateliers de concertations, de partages d’expériences et de meilleures pratiques et de réseautage des filières agricoles, des coopératives de production et de transformation et des autres acteurs de développement','3','75 000 FCFA'],
  ['08','gouvernance','Évaluation des impacts de la mise en œuvre des projets/initiatives de développement : apprentissage, capitalisation des leçons apprises et partage d’expériences et de meilleures pratiques','3','75 000 FCFA'],
  ['09','gouvernance','Accompagnement et renforcement des capacités de plaidoyer des acteurs des Collectivités territoriales pour la prévention et/ou l’atténuation des Risques de Catastrophes dans l’élaboration de leurs Plans Communaux de Développement','3','75 000 FCFA'],
  ['01','communication','Formation et renforcement des capacités des leaders associatifs et communautaires pour la maîtrise de la stratégie de plaidoyer (ciblages, argumentaires, messages clés, …) et le déroulement de sessions de plaidoyer pour l’adoption de décisions favorables au Changement','3','75 000 FCFA'],
  ['02','communication','Formation et renforcement des capacités des leaders communautaires (ONG, OSC, …) et chefs de projets en stratégies de Communication et de Mobilisation des communautés pour la mise en œuvre des projets de développement','2','50 000 FCFA'],
  ['03','communication','Formation à la Conception et à la réalisation des supports de communication (film documentaire, boîtes à images, photos d’exposition, …) sur la promotion des concepts de développement','3','75 000 FCFA'],
  ['04','communication','Formation sur le leadership genre et la prise de parole en public','2','75 000 FCFA'],
  ['01','management','De l’idée de projet à sa clôture : les principales articulations d’un cycle de projet (formulation, étude diagnostique, élaboration, planification stratégique et opérationnelle, mise en œuvre, suivi et évaluation, …)','3','75 000 FCFA'],
  ['02','management','Conception et planification stratégique et opérationnelle des projets de développement','3','75 000 FCFA'],
  ['03','management','Conception et planification stratégique et opérationnelle des projets humanitaires','3','75 000 FCFA'],
  ['04','management','Évaluation des impacts de la mise en œuvre des projets/initiatives de développement : apprentissage, capitalisation des leçons apprises et partage d’expériences et de meilleures pratiques','3','75 000 FCFA'],
  ['05','management','Conception et planification stratégique et opérationnelle des projets dans un contexte de crise sécuritaire','2','50 000 FCFA'],
  ['06','management','Planification, budgétisation et évaluation genre sensible des projets et programmes de développement et/ou humanitaires','2','50 000 FCFA'],
  ['07','management','Gestion des Projets Axée sur les Résultats (GAR) et Gestion Axée sur les Résultats de Développement (GRD)','2','50 000 FCFA'],
  ['08','management','Le travail d’équipe : Renforcer la cohésion, la complémentarité et la motivation de l’équipe de projet et du personnel','2','50 000 FCFA'],
  ['09','management','Formation et renforcement des capacités sur le Développement Institutionnel et le Renforcement Opérationnel (DIRO) des institutions, des organisations et des programmes de développement','2','50 000 FCFA'],
  ['10','management','Le Développement personnel : leadership, coaching et feed-back','2','50 000 FCFA'],
  ['01','decentralisation','Formation et renforcement des capacités des acteurs et des partenaires des collectivités territoriales sur les enjeux et les défis de la décentralisation et sur la conception et la réalisation des ouvrages communaux','3','75 000 FCFA'],
  ['02','decentralisation','Plaidoyer et stratégie de plaidoyer pour une approche participative et inclusive de tous les acteurs pour la gestion des affaires des collectivités décentralisées','3','75 000 FCFA'],
  ['01','intermediation','Formation et renforcement des capacités des acteurs du secteur privé sur les pools compétitifs des marchés émergents','3','75 000 FCFA'],
  ['01','terrain','Formation et renforcement des capacités sur les techniques de collecte et d’analyse des données d’enquêtes ou d’étude terrain','3','75 000 FCFA'],
] as const

const services = [
  ['01','Genre et Réduction des Inégalités','fa-venus-mars',['Formation et renforcement des capacités des acteurs','Plaidoyer pour l’égalité et les droits des femmes','Prévention et prise en charge des VBG','Planification et budgétisation genre sensible','Audits et évaluations d’impact genre sensible']],
  ['02','Amélioration des Politiques Publiques et de la Gouvernance','fa-landmark',['Études diagnostiques et recherches terrain','Redevabilité et gestion des plaintes','Approche basée sur les droits humains (ABDH)','Mobilisation endogène des ressources','Capitalisation des expériences et meilleures pratiques']],
  ['03','Communication et Marketing Social','fa-bullhorn',['Stratégies de communication et de mobilisation','Communication pour le développement et CCC','Conception de films, boîtes à images et supports','Marketing social et rebranding','Campagnes de plaidoyer et changement de comportement']],
  ['04','Management des Projets/Programmes de Développement','fa-diagram-project',['Conception et planification stratégique et opérationnelle','Montage, gestion et suivi-évaluation de projets','Gestion Axée sur les Résultats (GAR/GRD)','Développement institutionnel et renforcement opérationnel (DIRO)','Coaching, leadership et cohésion d’équipe']],
  ['05','Décentralisation et Gouvernance Locale','fa-city',['Plans de développement des collectivités (PCD, PRD)','Études de faisabilité d’ouvrages communaux','Dialogue communautaire et gestion des ressources','Coopération décentralisée et jumelage','Voyages d’études et échanges d’expériences']],
  ['06','Intermédiation Commerciale et Financière','fa-arrows-to-circle',['Prospection de marchés émergents','Mise en relation d’acteurs économiques','Mobilisation de ressources et facilitation financière','Négociation d’affaires et techniques managériales','Voyages d’affaires, foires et forums']],
  ['07','De la théorie à la pratique','fa-route',['Formation et renforcement des capacités des acteurs','Études diagnostiques, enquêtes et recherches terrain','Conception de stratégies et plans opérationnels','Audits, évaluations d’impact et capitalisation','Accompagnement agro-sylvo-pastoral et agro-industrie','Outils de gestion, communication et plaidoyer','Visites terrain, voyages d’études et expositions']],
] as const

const esc = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char] || char))
const themeById = (id: string) => themes.find((theme) => theme.id === id) || themes[0]

app.post('/api/contact', async (c) => {
  try {
    const body = await c.req.json()
    const { nom, email, message } = body
    if (!nom || !email || !message) return c.json({ success: false, error: 'Champs obligatoires manquants.' }, 400)
    return c.json({ success: true, message: 'Votre message a bien été reçu. L’équipe AFRIDEX vous recontactera dans les meilleurs délais.' })
  } catch {
    return c.json({ success: false, error: 'Erreur lors du traitement de votre message.' }, 500)
  }
})

app.get('*', (c) => c.html(getFullPage(c.req.path)))

function getFullPage(path: string): string {
  const formationsJson = JSON.stringify(formations.map(([number, theme, title, duration, cost]) => ({ number, theme, title, duration, cost, themeTitle: themeById(theme).title })))
  const courseSchema = JSON.stringify({ '@context': 'https://schema.org', '@type': 'ItemList', name: 'Catalogue des Formations AFRIDEX 2026', numberOfItems: formations.length, itemListElement: formations.map(([number, theme, title, duration, cost], index) => ({ '@type': 'ListItem', position: index + 1, item: { '@type': 'Course', name: title, provider: { '@type': 'Organization', name: 'AFRIDEX – Afrique Expertise' }, duration: `P${duration}D`, offers: { '@type': 'Offer', price: cost.replace(/[^0-9]/g, ''), priceCurrency: 'XOF' }, location: { '@type': 'Place', name: 'Ouagadougou, Burkina Faso' } } })) })
  const serviceHtml = services.map(([number, title, icon, items]) => `<article class="service-card service-card-${number}"><div class="service-number">${number}</div><div class="service-icon"><i class="fas ${icon}"></i></div><h3>${title}</h3><ul>${items.map((item) => `<li><i class="fas fa-check"></i>${item}</li>`).join('')}</ul><a href="#contact" class="service-link">Parlons de ce besoin <i class="fas fa-arrow-right"></i></a></article>`).join('')
  const themeHtml = themes.map((theme) => `<button class="theme-card theme-${theme.color}" data-theme="${theme.id}"><span class="theme-icon"><i class="fas ${theme.icon}"></i></span><span class="theme-number">${theme.number}</span><strong>${theme.title}</strong><small>${theme.short}</small><span class="theme-arrow"><i class="fas fa-arrow-right"></i></span></button>`).join('')
  const courseCards = formations.map(([number, theme, title, duration, cost], index) => `<article class="course-card" data-theme="${theme}" data-duration="${duration}" data-cost="${cost.startsWith('50') ? '50000' : '75000'}" data-title="${esc(title.toLowerCase())}"><div class="course-top"><span class="course-index">${String(index + 1).padStart(2, '0')}</span><span class="course-theme">${themeById(theme).title}</span></div><h3>${title}</h3><div class="course-meta"><span><i class="far fa-clock"></i>${duration} jours</span><span><i class="fas fa-location-dot"></i>Ouaga</span><b>${cost}</b></div><a class="course-cta" href="#contact" data-course="${esc(title)}">Demander une inscription <i class="fas fa-arrow-up-right-from-square"></i></a></article>`).join('')
  const tableRows = formations.map(([number, theme, title, duration, cost], index) => `<tr data-table-row="${index}"><td>${String(index + 1).padStart(2, '0')}</td><td><strong>${themeById(theme).title}</strong><span>${title}</span></td><td>${duration} jours</td><td>Ouagadougou</td><td><b>${cost}</b></td></tr>`).join('')
  const formationsPage = path.includes('formations')
  return `<!DOCTYPE html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${formationsPage ? 'Catalogue des Formations AFRIDEX 2026' : 'AFRIDEX – Afrique Expertise | Cabinet d’expertise au Burkina Faso'}</title><meta name="description" content="AFRIDEX accompagne les organisations avec des expertises en gouvernance, genre, communication, management de projets et formation au Burkina Faso et en Afrique de l’Ouest."><meta name="keywords" content="AFRIDEX, Burkina Faso, Ouagadougou, formation 2026, gouvernance, genre, projets, communication, consulting"><meta name="author" content="AFRIDEX – Afrique Expertise"><meta property="og:title" content="AFRIDEX – Afrique Expertise"><meta property="og:description" content="Des expertises qui transforment les défis du développement en décisions et en résultats."><meta property="og:type" content="website"><meta property="og:url" content="https://afridex.pages.dev"><link rel="icon" type="image/png" href="/static/images/logo-afridex.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.0/css/all.min.css" rel="stylesheet"><link href="/static/style.css" rel="stylesheet"><script type="application/ld+json">${courseSchema}</script></head><body data-page="${formationsPage ? 'formations' : 'home'}"><header id="header"><nav class="navbar"><div class="nav-container"><a href="/#accueil" class="nav-logo"><img src="/static/images/logo-afridex.png" alt="Logo AFRIDEX"><span>AFRI<span>DEX</span></span></a><button class="nav-toggle" id="navToggle" aria-label="Ouvrir le menu" aria-expanded="false"><span></span><span></span><span></span></button><ul class="nav-menu" id="navMenu"><li><a href="/#accueil" class="nav-link">Accueil</a></li><li><a href="/#a-propos" class="nav-link">À propos</a></li><li><a href="/#services" class="nav-link">Services</a></li><li><a href="/formations" class="nav-link nav-link-highlight">Formations <em>2026</em></a></li><li><a href="/#realisations" class="nav-link">Réalisations</a></li><li><a href="/#contact" class="nav-link">Contact</a></li><li><a href="/#contact" class="nav-btn-cta">Parler à AFRIDEX <i class="fas fa-arrow-up-right-from-square"></i></a></li></ul></div></nav></header><main>
<section id="accueil" class="hero-section"><div class="hero-grid"></div><div class="hero-orbit hero-orbit-one"></div><div class="hero-orbit hero-orbit-two"></div><div class="container hero-inner"><div class="hero-copy"><div class="eyebrow"><span></span> Cabinet d’expertises · Ouagadougou</div><h1>Transformer les défis en <em>trajectoires de progrès.</em></h1><p class="hero-lead">AFRIDEX met l’intelligence du terrain, la rigueur du conseil et la force des communautés au service d’un développement plus juste et plus durable.</p><div class="hero-actions"><a href="#services" class="btn btn-primary">Explorer nos expertises <i class="fas fa-arrow-right"></i></a><a href="/formations" class="btn btn-ghost">Catalogue 2026 <i class="fas fa-arrow-up-right-from-square"></i></a></div><div class="hero-proof"><div class="proof-avatars"><span>AF</span><span>BF</span><span>WA</span></div><p><strong>Une expertise ancrée à Ouagadougou</strong><br>pour agir au Burkina Faso, dans la sous-région et à l’international.</p></div></div><div class="hero-aside"><div class="hero-compass"><div class="compass-ring"></div><div class="compass-core"><i class="fas fa-location-arrow"></i><small>Cap sur<br>l’impact</small></div><span class="compass-label label-n">NORD</span><span class="compass-label label-s">TERRAIN</span><span class="compass-label label-e">EXPERTISE</span><span class="compass-label label-w">IMPACT</span></div><div class="hero-note"><span class="note-line"></span><div><small>Notre différence</small><strong>Des réponses qui<br>restent après la mission.</strong></div></div></div></div><div class="hero-bottom"><div class="container hero-stats"><div><strong data-count="7">7</strong><span>pôles d’expertise</span></div><div><strong data-count="35">35</strong><span>formations 2026</span></div><div><strong data-count="3">3</strong><span>jours pour passer à l’action</span></div><div><strong data-count="1">1</strong><span>ancrage : Ouagadougou</span></div></div></div></section>
<section class="signal-bar"><div class="container signal-inner"><span class="signal-kicker">AFRIDEX / 2026</span><p>Études · Conseil · Formation · Communication · Mise en œuvre</p><a href="/formations">Voir le calendrier <i class="fas fa-arrow-right"></i></a></div></section>
<section id="a-propos" class="section section-about"><div class="container split-layout"><div class="section-intro"><span class="section-label">01 / L’ADN AFRIDEX</span><h2>Comprendre le terrain avant de dessiner la solution.</h2><p>Nous sommes un cabinet burkinabè de consulting, de formation et de visibilité. Notre méthode : écouter les acteurs, clarifier les enjeux, construire des outils qui servent vraiment et transmettre les capacités.</p><a href="#contact" class="text-link">Construire avec nous <i class="fas fa-arrow-right"></i></a></div><div class="about-mosaic"><div class="mosaic-card mosaic-main"><span class="mosaic-mark">✳</span><strong>Rigueur<br>+ proximité</strong><small>La méthode n’a de valeur que lorsqu’elle devient utile.</small></div><div class="mosaic-card mosaic-small"><span>01</span><strong>Écouter</strong><small>Les voix du terrain</small></div><div class="mosaic-card mosaic-small mosaic-accent"><span>02</span><strong>Structurer</strong><small>Les décisions à prendre</small></div><div class="mosaic-card mosaic-wide"><span>03</span><strong>Transmettre</strong><small>Des compétences et des outils qui restent</small></div></div></div></section>
<section id="services" class="section section-services"><div class="container"><div class="section-heading-row"><div><span class="section-label">02 / NOS EXPERTISES</span><h2>Sept portes d’entrée.<br><em>Un même cap : l’impact.</em></h2></div><p>Du plaidoyer à la planification, AFRIDEX rassemble les compétences nécessaires pour relier stratégie, acteurs et résultats.</p></div><div class="services-grid">${serviceHtml}</div><div class="services-foot"><span>Chaque mission est conçue sur mesure.</span><a href="#contact" class="btn btn-dark">Décrire votre besoin <i class="fas fa-arrow-right"></i></a></div></div></section>
<section id="formations" class="section section-formations"><div class="container"><div class="formation-hero"><div><span class="section-label light">03 / TRANSMETTRE POUR TRANSFORMER</span><h2>Catalogue des<br><em>Formations AFRIDEX 2026</em></h2><p>35 parcours courts, concrets et directement reliés aux défis des organisations, des territoires et des communautés.</p><div class="formation-actions"><a class="btn btn-lime" href="/static/catalogue-afridex-2026.pdf" download><i class="fas fa-download"></i> Télécharger le catalogue PDF</a><a class="btn btn-outline-light" href="#contact">Organiser une session</a></div></div><div class="formation-total"><strong>35</strong><span>formations disponibles<br>en 2026</span><div class="total-rule"></div><small>7 thèmes · 2 ou 3 jours · Ouagadougou</small></div></div><div class="theme-grid">${themeHtml}</div><div class="catalogue-toolbar"><div class="catalogue-count"><strong id="courseCount">35</strong> formations affichées</div><label class="search-field"><i class="fas fa-search"></i><input id="courseSearch" type="search" placeholder="Rechercher une formation…" aria-label="Rechercher une formation"></label><select id="durationFilter" aria-label="Filtrer par durée"><option value="all">Toutes les durées</option><option value="2">2 jours</option><option value="3">3 jours</option></select><select id="costFilter" aria-label="Filtrer par coût"><option value="all">Tous les coûts</option><option value="50000">50 000 FCFA</option><option value="75000">75 000 FCFA</option></select><button id="resetFilters" class="filter-reset" type="button">Réinitialiser</button></div><div id="courseGrid" class="course-grid">${courseCards}</div><div id="emptyState" class="empty-state" hidden><i class="fas fa-compass"></i><h3>Aucune formation ne correspond</h3><p>Essayez un autre mot-clé ou réinitialisez les filtres.</p></div><details class="table-details"><summary><span>Voir le tableau récapitulatif complet</span><i class="fas fa-chevron-down"></i></summary><div class="table-wrap"><table><thead><tr><th>N°</th><th>Formation</th><th>Durée</th><th>Lieu</th><th>Coût</th></tr></thead><tbody>${tableRows}</tbody></table></div></details></div></section>
<section id="realisations" class="section section-impact"><div class="container"><div class="impact-header"><div><span class="section-label">04 / UNE CULTURE DU RÉSULTAT</span><h2>La preuve est dans<br><em>ce qui change.</em></h2></div><p>AFRIDEX intervient là où une décision doit être éclairée, une équipe renforcée, un dialogue renoué ou une stratégie mise en mouvement.</p></div><div class="impact-grid"><article><span class="impact-index">A</span><i class="fas fa-magnifying-glass-chart"></i><h3>Diagnostiquer</h3><p>Études, enquêtes et analyses pour donner aux décideurs une lecture juste de la situation.</p></article><article><span class="impact-index">B</span><i class="fas fa-people-group"></i><h3>Mobiliser</h3><p>Plaidoyer, communication et dialogue pour faire converger les énergies autour d’un changement.</p></article><article><span class="impact-index">C</span><i class="fas fa-seedling"></i><h3>Ancrer</h3><p>Des outils, des compétences et des plans qui continuent à produire des effets après la mission.</p></article></div></div></section>
<section id="contact" class="section section-contact"><div class="container contact-panel"><div class="contact-copy"><span class="section-label light">05 / PARLONS TERRAIN</span><h2>Une question.<br>Un territoire.<br><em>Un prochain pas.</em></h2><p>Décrivez-nous votre besoin : l’équipe AFRIDEX vous répondra avec une première piste claire.</p><div class="contact-details"><span><i class="fas fa-location-dot"></i> Quartier 14 Yaar, Ouagadougou</span><span><i class="fas fa-envelope"></i> contact@afridex.com</span><span><i class="fas fa-clock"></i> Lundi – Vendredi · 8h – 17h</span></div></div><form id="contactForm" class="contact-form"><div class="form-row"><label>Nom complet <input id="nom" name="nom" type="text" placeholder="Votre nom" required></label><label>Email <input id="email" name="email" type="email" placeholder="vous@organisation.org" required></label></div><label>Téléphone <input id="telephone" name="telephone" type="tel" placeholder="+226 XX XX XX XX"></label><label>Votre besoin <select id="sujet" name="sujet"><option value="">Choisir un sujet</option><option value="formation">Formation / renforcement des capacités</option><option value="expertise">Pôle d’expertise / prestation</option><option value="devis">Demande de devis</option><option value="partenariat">Partenariat</option><option value="autre">Autre</option></select></label><label>Message <textarea id="message" name="message" rows="4" placeholder="Parlez-nous de votre contexte et de votre objectif…" required></textarea></label><button type="submit" class="btn btn-lime">Envoyer la demande <i class="fas fa-arrow-right"></i></button><div id="formStatus" class="form-status" role="status" aria-live="polite"></div></form></div></section>
</main><footer class="footer"><div class="container footer-top"><div class="footer-brand"><a href="/#accueil" class="nav-logo"><img src="/static/images/logo-afridex.png" alt="Logo AFRIDEX"><span>AFRI<span>DEX</span></span></a><p>Cabinet d’expertises en consulting, en formation et en visibilité. Depuis Ouagadougou, pour l’Afrique.</p><div class="footer-social"><a href="https://www.facebook.com/afridex" aria-label="Facebook" target="_blank" rel="noopener"><i class="fab fa-facebook-f"></i></a><a href="https://www.tiktok.com/@afridex" aria-label="TikTok" target="_blank" rel="noopener"><i class="fab fa-tiktok"></i></a></div></div><div><h4>Explorer</h4><a href="/#a-propos">À propos</a><a href="/#services">Nos expertises</a><a href="/formations">Formations 2026</a><a href="/#realisations">Notre méthode</a></div><div><h4>Parler avec nous</h4><a href="/#contact">Demander un devis</a><a href="/#contact">Organiser une formation</a><a href="mailto:contact@afridex.com">contact@afridex.com</a><span>Quartier 14 Yaar<br>Ouagadougou, Burkina Faso</span></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} AFRIDEX – Afrique Expertise. Tous droits réservés.</span><span>Compétence · Proximité · Impact</span></div></footer><button id="scrollTopBtn" class="scroll-top-btn" aria-label="Retour en haut"><i class="fas fa-arrow-up"></i></button><script>window.__AFRIDEX_FORMATIONS__=${formationsJson}</script><script src="/static/app.js"></script></body></html>`
}

export default app
